import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Script src='https://code.createjs.com/1.0.0/createjs.min.js' strategy='beforeInteractive'/>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
